all:
  children:
    control_plane:
      hosts:
        cka-cp01:
          ansible_host: REPLACE_ME
    workers:
      hosts:
        cka-worker01:
          ansible_host: REPLACE_ME
  vars:
    ansible_user: cka
    kubernetes_version: "v1.37"
    pod_network_cidr: "10.244.0.0/16"
    flannel_version: "v0.28.8"
